from ui_mainwindow import Ui_MainWindow
from bracket_widget import Ui_BracketWidget
from ui_nowy_turniej import Ui_nowyTurniejForm
from ui_druzyny import Ui_druzynyForm
from ui_ustawienia import Ui_ustawieniaForm
from ui_okno_druzyny import Ui_oknoDruzynyForm
from ui_zawodnicy import Ui_zawodnicyForm
from ui_nastepny_mecz import Ui_nastepnyMeczForm
from ui_wczytaj_z_bazy import Ui_wczytajZBazyForm
from ui_najlepsi import Ui_najlepsiForm